### ISSUE TITLE
Add Optional to EncodingPlan.

### ISSUE THREAD

**Issue by Tomorrowdawn** [Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator#38] opened 2024-05-31 02:44 UTC
Thanks for your great work. I tested the performance of `env.view()`, but it costed approximately 1.2ms

```
%timeit game_state, encoded_state, reward, turn, done = env.view()
```

I modified the env.view() method to enforce it return a None encoded_state, the speed was significantly improved to 30us.

I deem this option necessary, since user might want to encode the states later, after collecting adequate data. A use case is offline RL. We will use many expert agents to collect data at first and post-process collected data for training.  

Supplementary:

And here is profile result for `env.step()`:

![image](https://github.com/Jarvis-Yu/Dottore-Genius-Invokation-TCG-Simulator/assets/61301081/40606eda-895a-4044-b917-fbf810f032f6)

It seems encoding costed most of the time. Disabling encoding would accelerate the data collection process significantly.

**Comment by Jarvis-Yu** [comment] 2024-05-31 03:05
Hi, thank you for your suggestion. This does sound necessary if you plan to do training in that way.

The code for `LinearEnv.step()` should be quite short and easy to modify, why not use the chance to submit a pull request?

If you do plan to submit one, I suggest you branch from `dev` branch, as it contains the latest code. I may take longer to actually implement this feature as there are too many other things to attend with. (bug issues, and other RL related stuff)

BTW, if you do plan to start doing RL recently, I suggest you to build the package from source with the script `scripts/sh/build.sh` in the repository and install it locally. As some latest commits have fixed certain bugs that may crash an ongoing game.

I am working on RL recently as well (that is why this simulator repo is having so few commits recently), and have implemented a class to encode actions and provide action masks. It is not fully implemented yet, (works only for AllOmniMode), but if you are interested, I can add it to `dev` branch to save you some time.

**Comment by Jarvis-Yu** [comment] 2024-05-31 03:10
Additionally, according to my experience, encoding & generating game states take only a small portion of the total training time. Model inferencing and training take the majority. (Just stating the fact, this doesn't imply the feature you want is insignificant)

**Comment by Tomorrowdawn** [comment] 2024-05-31 03:15
> Hi, thank you for your suggestion. This does sound necessary if you plan to do training in that way.
> 
> The code for `LinearEnv.step()` should be quite short and easy to modify, why not use the chance to submit a pull request?
> 
> If you do plan to submit one, I suggest you branch from `dev` branch, as it contains the latest code. I may take longer to actually implement this feature as there are too many other things to attend with. (bug issues, and other RL related stuff)
> 
> BTW, if you do plan to start doing RL recently, I suggest you to build the package from source with the script `scripts/sh/build.sh` in the repository and install it locally. As some latest commits have fixed certain bugs that may crash an ongoing game.
> 
> I am working on RL recently as well (that is why this simulator repo is having so few commits recently), and have implemented a class to encode actions and provide action masks. It is not fully implemented yet, (works only for AllOmniMode), but if you are interested, I can add it to `dev` branch to save you some time.

the key problem is whether it's appropriate for the step function to return the encoded state (which is why I opened an issue for such a simple question), as this may involve modifying the overall API. A seemingly reasonable architecture would be for the env to only return the state, while decoupling the encoding plan and turning it into a utility (since users may have any custom encoding). 

To implement this feature without modifying the API, we should probably modify the EncodingPlan base class to return None by default. I will complete this soon.

**Comment by Jarvis-Yu** [comment] 2024-05-31 03:19
I guess one way to do so is to replace all `game_state.encoding(self._encoding_plan, Pid(turn))` with `self._encoding_plan.encode(game_state, Pid(turn))`, enabling more freedom over the way how encoding works.

And of course, it is reasonable to want no time spent on `encoded_state` by just calling `.step()`, I agree with that.

**Comment by Jarvis-Yu** [comment] 2024-05-31 16:01
PR #39 regarding the issue is merged.

**Closed by Jarvis-Yu** 2024-05-31 16:01 UTC
